<?php


$deptos = array(
    1 => "Guatemala",
    2 => "El Progreso",
    3 => "Sacatepéquez",
    4 => "Chimaltenango",
    5 =>  "Escuintla",
    6 => "Santa Rosa",
    7 => "Sololá",
    8 => "Totonicapán",
    9 => "Quetzaltenango",
    10 => "Suchitepéquez",
    11 => "Retalhuleu",
    12 => "San Marcos",
    13 => "Huehuetenango",
    14 => "Quiché",
    15 => "Baja Verapaz",
    16 => "Alta Verapaz",
    18 => "Izabal",
    17 => "Petén",
    19 => "Zacapa",
    20 => "Chiquimula",
    21 => "Jalapa",
    22 => "Jutiapa",
);

$muni = array(
    "Guatemala" => array(
        'Municipio de Guatemala',
        'Santa Catarina Pinula',
        'San José Pinula',
        'San José del Golfo',
        'Palencia',
        'Chinautla',
        'San Pedro Ayampuc',
        'Mixco',
        'San Pedro Sacatepéquez',
        'San Juan Sacatepéquez',
        'San Raimundo',
        'Chuarrancho',
        'Fraijanes',
        'Amatitlán',
        'Villa Nueva',
        'Villa Canales',
        'Petapa',
    ),
    "El Progreso"  => array(
        'Guastatoya',
        'Morazán',
        'San Agustín Acasaguastlán',
        'San Cristobal Acasaguastlán',
        'El Jícaro',
        'Sansare',
        'Sanarate',
        'San Antonio La Paz',
    ),
    "Sacatepéquez" => array(
        'Antigua Guatemala',
        'Jocotenango',
        'Pastores',
        'Sumpango',
        'Santo Domingo Xenacoj',
        'Santiago Sacatepéquez',
        'San Bartolomé Milpas Altas',
        'San Lucas Sacatepéquez',
        'Santa Lucia Milpas Altas',
        'Magdalena Milpas Altas',
        'Santa María de Jesus',
        'Ciudad Vieja',
        'San Miguel Dueñas',
        'Alotenango',
        'San Antonio Aguas Calientes',
        'Santa Catalina Barahona',
    ),
    "Chimaltenango"  => array(
        'Chimaltenango',
        'San José Poaquil',
        'San MartÍn Jilotepeque',
        'Comalapa',
        'Santa Apolonia',
        'Tecpan Guatemala',
        'Patzun',
        'Pochuta',
        'Patzicía',
        'Santa Cruz Balanya',
        'Acatenango',
        'Yepocapa',
        'San Andrés Itzapa',
        'Parramos',
        'Zaragoza',
        'El Tejar'
    ),
    "Escuintla"  => array(
        'Escuintla',
        'Santa Lucía Cotzumalguapa',
        'La Democracia',
        'Siquinala',
        'Masagua',
        'Tiquisate',
        'La Gomera',
        'Guanagazapa',
        'San José',
        'Iztapa',
        'Palín',
        'San Vicente Pacaya'
    ),
    "Santa Rosa" => array(
        'Cuilapa',
        'Barberena',
        'Santa Rosa De Lima',
        'Casillas',
        'San Rafael Las Flores',
        'Oratorio',
        'San Juan Tecuaco',
        'Chiquimulilla',
        'Taxisco',
        'Santa María Ixhuatan',
        'Guazacapan',
        'Santa Cruz Naranjo',
        'Pueblo Nuevo Viñas',
        'Nueva Santa Rosa'
    ),
    "Sololá" => array(
        'Sololá',
        'San José Chacayá',
        'Santa María Visitación',
        'Santa Lucía Utatlan',
        'Nahuala',
        'Santa Catarina Ixtahuacan',
        'Santa Clara La Laguna',
        'Concepción',
        'San Andrés Semetabaj',
        'Panajachel',
        'Santa Catarina Palopó',
        'San Antonio Palopó',
        'San Lucas Tolimán',
        'Santa Cruz La Laguna',
        'San Pablo La Laguna',
        'San Marcos La Laguna',
        'San Juan La Laguna',
        'San Pedro La Laguna',
        'Santiago Atitlán'
    ),
    "Totonicapán" => array(
        'Totonicapán',
        'San Cristóbal Totonicapan',
        'San Francisco El Alto',
        'San Andrés Xecul',
        'Momostenango',
        'Santa María Chiquimula',
        'Santa Lucía La Reforma',
        'San Bartolo'
    ),
    "Quetzaltenango" => array(
        'Quetzaltenango',
        'Salcajá',
        'Olintepeque',
        'San Carlos Sija',
        'Sibilia',
        'Cabricán',
        'Cajolá',
        'San Miguel Siguilá',
        'Ostuncalco',
        'San Mateo',
        'Concepción Chiquirichapa',
        'San Martín Sacatepéquez',
        'Almolonga',
        'Cantel',
        'Huitán',
        'Zunil',
        'Colomba',
        'San Francisco La Unión',
        'El Palmar',
        'Coatepeque',
        'Génova',
        'Flores Costa Cuca',
        'La Esperanza',
        'Palestina de Los Altos',
    ),
    "Suchitepéquez" => array(
        'Mazatenango',
        'Cuyotenango',
        'San Francisco Zapotitlán',
        'San Bernardino',
        'San José El Idolo',
        'Santo Domingo Suchitepéquez',
        'San Lorenzo',
        'Samayac',
        'San Pablo Jocopilas',
        'San Antonio Suchitepéquez',
        'San Miguel Panán',
        'San Gabriel',
        'Chicacao',
        'Patulul',
        'Santa Barbara',
        'San Juan Bautista',
        'Santo Tomas La Unión',
        'Zunilito',
        'Pueblo Nuevo',
        'Río Bravo'
    ),
    "Retalhuleu" => array(
        'Retalhuleu',
        'San Sebastián',
        'Santa Cruz Muluá',
        'San Martín Zapotitlán',
        'San Felipe',
        'San Andrés Villa Seca',
        'Champerico',
        'Nuevo San Carlos',
        'El Asintal'
    ),
    "San Marcos" => array(
        'San Marcos',
        'San Pedro Sacatepéquez',
        'San Antonio Sacatepéquez',
        'Comitancillo',
        'San Miguel Ixtahuacán',
        'Concepción Tutuapa',
        'Tacaná',
        'Sibinal',
        'Tajumulco',
        'Tejutla',
        'San Rafael Pie De La Cuesta',
        'Nuevo Progreso',
        'El Tumbador',
        'El Rodeo',
        'Malacatán',
        'Catarina',
        'Ayutla',
        'Ocós',
        'San Pablo',
        'El Quetzal',
        'La Reforma',
        'Pajapita',
        'Ixchiguán',
        'San José Ojetenam',
        'San Cristóbal Cucho',
        'Sipacapa',
        'Esquipulas Palo Gordo',
        'Río Blanco',
        'San Lorenzo'
    ),
    "Huehuetenango" => array(
        'Huehuetenango',
        'Chiantla',
        'Malacatancito',
        'Cuilco',
        'Nentón',
        'San Pedro Necta',
        'Jacaltenango',
        'Soloma',
        'Ixtahuacán',
        'Santa Bárbara',
        'La Libertad',
        'La Democracia',
        'San Miguel Acatán',
        'San Rafael La Independencia',
        'Todos Santos Cuchumatánes',
        'San Juan Atitán',
        'Santa Eulalia',
        'San Mateo Ixtatán',
        'Colotenango',
        'San Sebastián Huehetenango',
        'Tectitán',
        'Concepción Huista',
        'San Juan Ixcoy',
        'San Antonio Huista',
        'San Sebastián Coatán',
        'Barillas',
        'Aguacatán',
        'San Rafael Petzal',
        'San Gaspar Ixchil',
        'Santiago Chimaltenango',
        'Santa Ana Huista'
    ),
    "Quiché" => array(
        'Santa Cruz del Quiché',
        'Chiché',
        'Chinique',
        'Zacualpa',
        'Chajul',
        'Chichicastenango',
        'Patzité',
        'San Antonio Ilotenango',
        'San Pedro Jocopilas',
        'Cunén',
        'San Juan Cotzal',
        'Joyabaj',
        'Nebaj',
        'San Andrés Sajcabajá',
        'Uspantán',
        'Sacapulas',
        'San Bartolomé Jocotenango',
        'Canillá',
        'Chicamán',
        'Ixcán',
        'Pachalum '
    ),
    "Baja Verapaz" => array(
        'Salamá',
        'San Miguel Chicaj',
        'Rabinal',
        'Cubulco',
        'Granados',
        'El Chol',
        'San Jerónimo',
        'Purulha'
    ),
    "Alta Verapaz" => array(
        'Cobán',
        'Santa Cruz Verapaz',
        'San Cristóbal Verapaz',
        'Tactic',
        'Tamahù',
        'Tucurú',
        'Panzós',
        'Senahú',
        'San Pedro Carchá',
        'San Juan Chamelco',
        'Lanquín',
        'Cahabón',
        'Chisec',
        'Chahal',
        'Fray Bartolomé de Las Casas'
    ),
    "Petén" => array(
        'Flores',
        'San José',
        'San Benito',
        'San Andrés',
        'La Libertad',
        'San Francisco',
        'Santa Ana',
        'Dolores',
        'San Luis',
        'Sayaxché',
        'Melchor De Mencos',
        'Poptún',
    ),
    "Izabal" => array(
        'Puerto Barrios',
        'Lívingston',
        'El Estor',
        'Morales',
        'Los Amates'
    ),
    "Zacapa" => array(
        'Zacapa',
        'Estanzuela',
        'Río Hondo',
        'Gualán',
        'Teculután',
        'Usumatlán',
        'Cabañas',
        'San Diego',
        'La Unión',
        'Huité'
    ),
    "Chiquimula"  => array(
        'Chiquimula',
        'San José La Arada',
        'San Juan Ermita',
        'Jocotán',
        'Camotán',
        'Olopa',
        'Esquipulas',
        'Concepción Las Minas',
        'Quetzaltepeque',
        'San Jacinto',
        'Ipala'
    ),
    "Jalapa" => array(
        'Jalapa',
        'San Pedro Pinula',
        'San Luis Jilotepeque',
        'San Manuel Chaparrón',
        'San Carlos Alzatate',
        'Monjas',
        'Mataquescuintla',
    ),
    "Jutiapa" => array(
        'Jutiapa',
        'El Progreso',
        'Santa Catarina Mita',
        'Agua Blanca',
        'Asunción Mita',
        'Yupiltepeque',
        'Atescatempa',
        'Jerez',
        'El Adelanto',
        'Zapotitlán',
        'Comapa',
        'Jalpatagua',
        'Conguaco',
        'Moyuta',
        'Pasaco',
        'San José Acatempa',
        'Quesada',
    ),
);
